"""
Django settings for payment_service project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import sys, os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")
PAYMENT_LINK_CALLBACK_URL = os.getenv("PAYMENT_LINK_CALLBACK_URL")
ORDER_UPDATE_QUEUE_URL = os.getenv("ORDER_UPDATE_QUEUE_URL")
PAYMENT_UPDATE_QUEUE_URL = os.getenv("PAYMENT_UPDATE_QUEUE_URL")
AWS_REGION = os.getenv("AWS_REGION")
PAYMENT_SERVICE_BASE_URL = os.getenv("PAYMENT_SERVICE_BASE_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3)nsiap1!67pd5y&vh=b*(*2y7%n+do(b=cm-69kqhvzcp$-%v"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "payments",
    "rest_framework",
    "drf-yasg"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "payments.custom_middlewares.CorrelationIdMiddleware",
]

ROOT_URLCONF = "payment_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "payment_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Important: keep Django's default logging alive
    'formatters': {
        'default': {
            'format': '{"timestamp": %(asctime)s, "severity": %(levelname)s, "logger": %(name)s, "function": %(funcName)s, "line": %(lineno)d, "correlation_id": %(correlation_id)s, "message": %(message)s}',
            'style': '%',  # Ensure we're using the '%' style
        },
    },
    'filters': {
        'correlation_id_filter': {
            '()': 'payments.utils.CorrelationIdFilter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
            'filters': ['correlation_id_filter'],
            'stream': sys.stdout,
        },
        # 'cloudwatch': {  <-- Later, just add this
        #     'class': 'watchtower.CloudWatchLogHandler',
        #     'log_group': 'your-log-group-name',
        #     'stream_name': 'your-stream-name',
        #     'formatter': 'default',
        #     'filters': ['correlation_id_filter'],
        # },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',  # Can set DEBUG in local dev
            'propagate': True,
        },
        'payments': {  # <-- Your custom app logger
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

APPEND_SLASH = True