version: "3.9"

services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    volumes:
      - ./user_service:/app

  product_service:
    build: ./product_service
    ports:
      - "8001:8001"
    volumes:
      - ./product_service:/app

  order_service:
    build: ./order_service
    ports:
      - "8002:8002"
    volumes:
      - ./order_service:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SQS_QUEUE_URL=http://localstack:4566/000000000000/order-queue
    depends_on:
      - localstack

  payment_service:
    build: ./payment_service
    ports:
      - "8003:8003"
    volumes:
      - ./payment_service:/app
    environment:
      - RAZORPAY_KEY_ID=dummy
      - RAZORPAY_KEY_SECRET=dummy
      - PAYMENT_LINK_CALLBACK_URL=http://order_service:8002/payment/callback
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SQS_QUEUE_URL=http://localstack:4566/000000000000/payment-queue
    depends_on:
      - localstack

  order_worker:
    build: ./order_service
    command: python manage.py poll_sqs
    depends_on:
      - order_service
      - localstack
      - init_localstack

  payment_worker:
    build: ./payment_service
    command: python manage.py poll_sqs
    depends_on:
      - payment_service
      - localstack
      - init_localstack

  localstack:
    image: localstack/localstack:4.5
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
    volumes:
      - ./localstack:/etc/localstack
      - localstack_data:/var/lib/localstack

  init_localstack:
    image: localstack/localstack:4.5
    depends_on:
      - localstack
    entrypoint: /bin/bash
    command: -c "chmod +x /init_localstack.sh && /init_localstack.sh"
    volumes:
      - ./init_localstack.sh:/init_localstack.sh:ro

volumes:
  localstack_data:
