# Generated by Django 5.2 on 2025-05-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "auditlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.auditlog",
                    ),
                ),
                ("order_id", models.CharField(max_length=255)),
                (
                    "razorpay_order_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("status", models.CharField(max_length=50)),
                ("receipt", models.CharField(max_length=255, unique=True)),
            ],
            bases=("payments.auditlog",),
        ),
    ]
