# Generated by Django 5.2 on 2025-05-02 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="razorpay_order_id",
            new_name="razorpay_payment_link_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="razorpay_payment_id",
            new_name="razorpay_short_url",
        ),
    ]
