# Generated by Django 5.2 on 2025-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0002_rename_razorpay_order_id_payment_razorpay_payment_link_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
