# Generated by Django 5.2 on 2025-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
