# Generated by Django 5.2 on 2025-04-27 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_orderitem_orderitems_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="product",
            new_name="product_id",
        ),
    ]
